katalog/urls.py
from django.urls import path
from katalog.views import request_catalogs

appname = 'katalog'

urlpatterns = [
    path('', request_catalogs, name='request_catalogs')
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

import wishlist

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
    path('wishlist/',include("wishlist.urls") )
]

# TODO: Implement Routings Here

todolist/urls.py
from django.urls import path
from todolist.views import  delete, register, login_user, logout_user, show_todos, new_task, refresh, new

app_name = "todolist"

#routing url 
urlpatterns = [
    path('', show_todos, name='show_todos'),
    path('login/', login_user, name='login_user'),
    path('register/', register, name='register'),
    path('create-task/', new_task, name='new_task'),
    path('logout/', logout_user, name='logout_user'),
    path('refresh/<str:id>/', refresh, name="refresh"),
    path('delete/<str:id>/', delete, name="delete"),
    path('new/', new, name='new')
]

todolist/models.py
from gc import is_finalized
from django.db import models
from django.contrib.auth.models import User
# ref : https://www.youtube.com/watch?v=zJWhizYFKP0

# Create your models here.
class Tasks(models.Model):
    user = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    # ref : https://docs.djangoproject.com/en/4.1/ref/models/fields/ 
    date = models.DateField(auto_now=True)
    title = models.CharField(max_length=255)
    description = models.TextField()
    is_finished = models.BooleanField(default=False)

todolist/forms.py
from django.forms import ModelForm
from todolist.models import Tasks

class TaskForm(ModelForm):
    class Meta:
        model = Tasks
        fields = ['title', 'description']

todolist/views.py
import datetime
from django.shortcuts import render
from todolist.models import Tasks
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from todolist.forms import TaskForm
from django.urls import reverse

# Create your views here.
def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Account successfully created!')
            return redirect('todolist:login_user')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # login first
            response = HttpResponseRedirect(reverse("todolist:show_todos")) # create response
            response.set_cookie('username', username)
            response.set_cookie('last_login', str(datetime.datetime.now())) # create last_login cookie and add it to response
            return response
        else:
            messages.info(request, 'Wrong Username or Password!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login_user'))
    response.delete_cookie('last_login')
    return response

@login_required(login_url='/todolist/login/') # login first before doing this
def show_todos(request):
    # filters the user, so that each user can have their own todolist
    data = Tasks.objects.filter(user = request.user)
    context = {
        # using cookies since it is a rememberable temporary data
        'username': request.COOKIES['username'],
        'last_login': request.COOKIES['last_login'],
        'todos': data,

    }
    return render(
        request,
        'todolist.html',
        context
    )

@login_required(login_url='/todolist/login/') # login first before doing this
def new(request):
    # filters the user, so that each user can have their own todolist
    data = Tasks.objects.filter(user = request.user)
    context = {
        # using cookies since it is a rememberable temporary data
        'username': request.COOKIES['username'],
        'last_login': request.COOKIES['last_login'],
        'todos': data,

    }
    return render(
        request,
        'newtodolist.html',
        context
    )

@login_required(login_url='/todolist/login/') # login first before doing this
def new_task(request):
    form = TaskForm()
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            form_check = form.save(commit=False)
            form_check.user = request.user
            form_check.save()
            return HttpResponseRedirect(reverse('todolist:show_todos'))
        else:
            messages.info(request, "There's a problem with the data, please try again")
    
    # when requesting 
    return render(request, 'new_task.html', {'form': form})
            

    ...

@login_required(login_url='/todolist/login/') # login first before doing this
def refresh(request, id):
    task = Tasks.objects.get(user = request.user, pk = id)
    task.is_finished = not task.is_finished
    task.save()
    return redirect('todolist:show_todos')
    ...

@login_required(login_url='/todolist/login/') # login first before doing this
def delete(request, id):
    task = Tasks.objects.get(user = request.user, pk = id)
    task.delete()
    return redirect('todolist:show_todos')

todolist/templates/login.html
{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}
<div
  style="
    display: flex;
    flex-direction: column;
    height: 454px;
  "
  class="Canvas"
  ><div
    style="flex-grow: 1; display: flex"
    class="Canvas Body"
    ><div
      style="
        width: 100%;
        height: 100%;
        display: flex;
        position: relative;
        justify-content: center;
        box-sizing: border-box;
      "
      class="Canvas Placeholder for MacBook Air - 3"
      ><div
        style="
          width: 1280px;
          height: 100px;
          display: flex;
          position: absolute;
          left: 0;
          top: 0;
          background-color: #045fd4;
          border-radius: 0px 0px 30px 30px;
          box-sizing: border-box;
        "
        class="Rectangle 18"
      ></div
      ><p
        style="
          display: flex;
          position: absolute;
          left: 344px;
          top: -1px;
          justify-content: flex-start;
          text-align: left;
          margin: 0;
          box-sizing: border-box;
          font-size: 80px;
          font-family: SF UI Text;
          font-weight: 700;
          color: white;
          letter-spacing: 0;
          text-overflow: ellipsis;
          overflow: hidden;
        "
        >To-do List App</p
      ><div
        style="
          width: 300px;
          height: 300px;
          display: flex;
          position: absolute;
          left: 432px;
          top: 124px;
          background-color: #c42f21;
          border-radius: 30px;
          box-sizing: border-box;
        "
        class="Rectangle 18"
      ></div
      ><div
        style="
          width: 300px;
          height: 50px;
          display: flex;
          position: absolute;
          left: 432px;
          top: 374px;
          background-color: white;
          border-radius: 0px 0px 30px 30px;
          box-sizing: border-box;
        "
        class="Rectangle 20"
        ><div
          style="
            width: 100%;
            height: 100%;
            position: absolute;
            box-sizing: border-box;
            border: 1px solid black;
            border-radius: 0px 0px 30px 30px;
          "
        ></div></div
      ><div
        style="
          width: 250px;
          height: 40px;
          display: flex;
          position: absolute;
          left: 457px;
          top: 228px;
          background-color: white;
          border-radius: 20px;
          box-sizing: border-box;
        "
        class="Rectangle 19"
        ><div
          style="
            width: 100%;
            height: 100%;
            position: absolute;
            box-sizing: border-box;
            border: 1px solid #045fd4;
            border-radius: 20px;
          "
        ></div></div
      ><p
        style="
          display: flex;
          position: absolute;
          left: 469px;
          top: 210px;
          justify-content: flex-start;
          text-align: left;
          margin: 0;
          box-sizing: border-box;
          font-size: 10px;
          font-family: SF UI Text;
          font-weight: 700;
          color: white;
          letter-spacing: 0;
          text-overflow: ellipsis;
          overflow: hidden;
        "
        >Username</p
      ><p
        style="
          display: flex;
          position: absolute;
          left: 476px;
          top: 238px;
          justify-content: flex-start;
          text-align: left;
          margin: 0;
          box-sizing: border-box;
          font-size: 13px;
          font-family: SF UI Text;
          font-weight: 700;
          color: rgba(0, 0, 0, 0.5);
          letter-spacing: 0;
          text-overflow: ellipsis;
          overflow: hidden;
        "
        >ex : dylanpribadi</p
      ><div
        style="
          width: 250px;
          height: 40px;
          display: flex;
          position: absolute;
          left: 457px;
          top: 299px;
          background-color: white;
          border-radius: 20px;
          box-sizing: border-box;
        "
        class="Rectangle 19"
        ><div
          style="
            width: 100%;
            height: 100%;
            position: absolute;
            box-sizing: border-box;
            border: 1px solid #045fd4;
            border-radius: 20px;
          "
        ></div></div
      ><p
        style="
          display: flex;
          position: absolute;
          left: 469px;
          top: 281px;
          justify-content: flex-start;
          text-align: left;
          margin: 0;
          box-sizing: border-box;
          font-size: 10px;
          font-family: SF UI Text;
          font-weight: 700;
          color: white;
          letter-spacing: 0;
          text-overflow: ellipsis;
          overflow: hidden;
        "
        >Password</p
      ><p
        style="
          display: flex;
          position: absolute;
          left: 474px;
          top: 310px;
          justify-content: flex-start;
          text-align: left;
          margin: 0;
          box-sizing: border-box;
          font-size: 13px;
          font-family: SF UI Text;
          font-weight: 700;
          color: rgba(0, 0, 0, 0.5);
          letter-spacing: 0;
          text-overflow: ellipsis;
          overflow: hidden;
        "
        >please type a strong password</p
      ><p
        style="
          display: flex;
          position: absolute;
          left: 512px;
          top: 136px;
          justify-content: flex-start;
          text-align: left;
          margin: 0;
          box-sizing: border-box;
          font-size: 50px;
          font-family: SF UI Text;
          font-weight: 700;
          color: white;
          letter-spacing: 0;
          text-overflow: ellipsis;
          overflow: hidden;
        "
        >Login</p
      ><p
        style="
          display: flex;
          position: absolute;
          left: 506px;
          top: 390px;
          justify-content: flex-start;
          text-align: left;
          margin: 0;
          box-sizing: border-box;
          font-size: 13px;
          font-family: SF UI Text;
          font-weight: 700;
          color: black;
          letter-spacing: 0;
          text-overflow: ellipsis;
          overflow: hidden;
        "
        >Forgot your password?</p
      ></div
    ></div
  ></div
>

{% endblock content %}

todolist/templates/new_task.html
{% block meta %}
<title>Create Task</title>
{% endblock meta %}

{% block content %}  

<div
  style="
    display: flex;
    flex-direction: column;
    height: 454px;
  "
  class="Canvas"
  ><div
    style="flex-grow: 1; display: flex"
    class="Canvas Body"
    ><div
      style="
        width: 100%;
        height: 100%;
        display: flex;
        position: relative;
        justify-content: center;
        box-sizing: border-box;
      "
      class="Canvas Placeholder for MacBook Air - 4"
      ><div
        style="
          width: 1280px;
          height: 100px;
          display: flex;
          position: absolute;
          left: 0;
          top: 0;
          background-color: #045fd4;
          border-radius: 0px 0px 30px 30px;
          box-sizing: border-box;
        "
        class="Rectangle 18"
      ></div
      ><p
        style="
          display: flex;
          position: absolute;
          left: 344px;
          top: -1px;
          justify-content: flex-start;
          text-align: left;
          margin: 0;
          box-sizing: border-box;
          font-size: 80px;
          font-family: SF UI Text;
          font-weight: 700;
          color: white;
          letter-spacing: 0;
          text-overflow: ellipsis;
          overflow: hidden;
        "
        >To-do List App</p
      ><div
        style="
          width: 300px;
          height: 300px;
          display: flex;
          position: absolute;
          left: 432px;
          top: 124px;
          background-color: #c42f21;
          border-radius: 30px;
          box-sizing: border-box;
        "
        class="Rectangle 18"
      ></div
      ><div
        style="
          width: 300px;
          height: 50px;
          display: flex;
          position: absolute;
          left: 432px;
          top: 374px;
          background-color: white;
          border-radius: 0px 0px 30px 30px;
          box-sizing: border-box;
        "
        class="Rectangle 20"
        ><div
          style="
            width: 100%;
            height: 100%;
            position: absolute;
            box-sizing: border-box;
            border: 1px solid black;
            border-radius: 0px 0px 30px 30px;
          "
        ></div></div
      ><div
        style="
          width: 250px;
          height: 40px;
          display: flex;
          position: absolute;
          left: 457px;
          top: 228px;
          background-color: white;
          border-radius: 20px;
          box-sizing: border-box;
        "
        class="Rectangle 19"
        ><div
          style="
            width: 100%;
            height: 100%;
            position: absolute;
            box-sizing: border-box;
            border: 1px solid #045fd4;
            border-radius: 20px;
          "
        ></div></div
      ><p
        style="
          display: flex;
          position: absolute;
          left: 469px;
          top: 210px;
          justify-content: flex-start;
          text-align: left;
          margin: 0;
          box-sizing: border-box;
          font-size: 10px;
          font-family: SF UI Text;
          font-weight: 700;
          color: white;
          letter-spacing: 0;
          text-overflow: ellipsis;
          overflow: hidden;
        "
        >Title</p
      ><p
        style="
          display: flex;
          position: absolute;
          left: 476px;
          top: 238px;
          justify-content: flex-start;
          text-align: left;
          margin: 0;
          box-sizing: border-box;
          font-size: 13px;
          font-family: SF UI Text;
          font-weight: 700;
          color: rgba(0, 0, 0, 0.5);
          letter-spacing: 0;
          text-overflow: ellipsis;
          overflow: hidden;
        "
        >ex : Taking a Bath</p
      ><div
        style="
          width: 250px;
          height: 40px;
          display: flex;
          position: absolute;
          left: 457px;
          top: 299px;
          background-color: white;
          border-radius: 20px;
          box-sizing: border-box;
        "
        class="Rectangle 19"
        ><div
          style="
            width: 100%;
            height: 100%;
            position: absolute;
            box-sizing: border-box;
            border: 1px solid #045fd4;
            border-radius: 20px;
          "
        ></div></div
      ><p
        style="
          display: flex;
          position: absolute;
          left: 469px;
          top: 281px;
          justify-content: flex-start;
          text-align: left;
          margin: 0;
          box-sizing: border-box;
          font-size: 10px;
          font-family: SF UI Text;
          font-weight: 700;
          color: white;
          letter-spacing: 0;
          text-overflow: ellipsis;
          overflow: hidden;
        "
        >Description</p
      ><p
        style="
          display: flex;
          position: absolute;
          left: 474px;
          top: 310px;
          justify-content: flex-start;
          text-align: left;
          margin: 0;
          box-sizing: border-box;
          font-size: 13px;
          font-family: SF UI Text;
          font-weight: 700;
          color: rgba(0, 0, 0, 0.5);
          letter-spacing: 0;
          text-overflow: ellipsis;
          overflow: hidden;
        "
        >I will take a bath soon</p
      ><p
        style="
          display: flex;
          position: absolute;
          left: 460px;
          top: 136px;
          justify-content: flex-start;
          text-align: left;
          margin: 0;
          box-sizing: border-box;
          font-size: 50px;
          font-family: SF UI Text;
          font-weight: 700;
          color: white;
          letter-spacing: 0;
          text-overflow: ellipsis;
          overflow: hidden;
        "
        >New Task</p
      ><p
        style="
          display: flex;
          position: absolute;
          left: 489px;
          top: 392px;
          justify-content: flex-start;
          text-align: left;
          margin: 0;
          box-sizing: border-box;
          font-size: 13px;
          font-family: SF UI Text;
          font-weight: 700;
          color: black;
          letter-spacing: 0;
          text-overflow: ellipsis;
          overflow: hidden;
        "
        >When?</p
      ><img
        src="https://firebasestorage.googleapis.com/v0/b/codeless-app.appspot.com/o/projects%2F6FKZtubSF8RSvZrAnUp7%2Fd531e04cde59a1cfbc37e75bea54e2eb?alt=media&amp;token=33e7e21e-8d7e-4299-ba91-e669f65863ef"
        class="img child Rectangle 21, Vector 1, Vector 1"
        style="
          width: 90px;
          height: 20px;
          display: flex;
          position: absolute;
          left: 550px;
          top: 391px;
          box-sizing: border-box;
        "
      /><p
        style="
          display: flex;
          position: absolute;
          left: 553px;
          top: 392px;
          justify-content: flex-start;
          text-align: left;
          margin: 0;
          box-sizing: border-box;
          font-size: 13px;
          font-family: SF UI Text;
          font-weight: 700;
          color: white;
          letter-spacing: 0;
          text-overflow: ellipsis;
          overflow: hidden;
        "
        >22</p
      ><p
        style="
          display: flex;
          position: absolute;
          left: 581px;
          top: 392px;
          justify-content: flex-start;
          text-align: left;
          margin: 0;
          box-sizing: border-box;
          font-size: 13px;
          font-family: SF UI Text;
          font-weight: 700;
          color: white;
          letter-spacing: 0;
          text-overflow: ellipsis;
          overflow: hidden;
        "
        >Dec</p
      ><p
        style="
          display: flex;
          position: absolute;
          left: 618px;
          top: 392px;
          justify-content: flex-start;
          text-align: left;
          margin: 0;
          box-sizing: border-box;
          font-size: 13px;
          font-family: SF UI Text;
          font-weight: 700;
          color: white;
          letter-spacing: 0;
          text-overflow: ellipsis;
          overflow: hidden;
        "
        >22</p
      ></div
    ></div
  ></div
>

{% endblock content %}

todolist/templates/newtodolist.html
{% block content %}  
<div
  style="
    display: flex;
    flex-direction: column;
    height: 832px;
  "
  class="Canvas"
  ><div
    style="flex-grow: 1; display: flex"
    class="Canvas Body"
    ><div
      style="
        width: 100%;
        height: 100%;
        display: flex;
        position: relative;
        justify-content: center;
        box-sizing: border-box;
      "
      class="Canvas Placeholder for MacBook Air - 1"
      ><p
        style="
          display: flex;
          position: absolute;
          left: 199px;
          top: 18px;
          justify-content: flex-start;
          text-align: left;
          margin: 0;
          box-sizing: border-box;
          font-size: 100px;
          font-family: SF UI Text;
          font-weight: 700;
          color: black;
          letter-spacing: 0;
          text-overflow: ellipsis;
          overflow: hidden;
        "
        >Registration Form</p
      ></div
    ></div
  ></div
>
{% endblock content %}

todolist/templates/todolist.html
{% block content %}

<!-- <h1>Username: {{ username }} </h1>
<h2>To-do list app!</h2>

<table cellspacing = "32">
    
  <thead>
    <tr>
        <th>Date</th>
        <th>Title</th>
        <th>Description</th>
        <th>Status</th>
        <th>Options</th>
    </tr>
  </thead>
  <tbody>
    {% for todo in todos %}
    <tr>
      <td>{{ todo.date }}</td>
      <td>{{ todo.title }}</td>
      <td>{{ todo.description }}</td>
      {% if todo.is_finished %}
        <td>Done</td>
      {% else %}
        <td>In Progress</td>
      {% endif %}
      <td>
        <a href="{% url 'todolist:refresh' todo.pk %}">Toggle</a>
        <a href="{% url 'todolist:delete' todo.pk %}" >Delete</a>
      </td>
    </tr>
  {% endfor %}
  </tbody>

</table>

<a href="{% url 'todolist:logout_user' %}", class="custom-alert-button">Logout</a>
<a href="{% url 'todolist:new_task' %}", class="custom-primary-button">Create Task</a> -->

<div
  style="
    display: flex;
    flex-direction: column;
    height: 832px;
  "
  class="Canvas"
  ><div
    style="flex-grow: 1; display: flex"
    class="Canvas Body"
    ><div
      style="
        width: 100%;
        height: 100%;
        display: flex;
        position: relative;
        justify-content: center;
        box-sizing: border-box;
      "
      class="Canvas Placeholder for MacBook Air - 2"
      ><div
        style="
          width: 1280px;
          height: 100px;
          display: flex;
          position: absolute;
          left: 0;
          top: 0;
          background-color: #045fd4;
          border-radius: 0px 0px 30px 30px;
          box-sizing: border-box;
        "
        class="Rectangle 17"
      ></div
      ><p
        style="
          display: flex;
          position: absolute;
          left: 344px;
          top: -1px;
          justify-content: flex-start;
          text-align: left;
          margin: 0;
          box-sizing: border-box;
          font-size: 80px;
          font-family: SF UI Text;
          font-weight: 700;
          color: white;
          letter-spacing: 0;
          text-overflow: ellipsis;
          overflow: hidden;
        "
        >To-do List App</p
      ><div
        style="
          width: 300px;
          height: 300px;
          display: flex;
          position: absolute;
          left: 18px;
          top: 116px;
          background-color: #c42f21;
          border-radius: 30px;
          box-sizing: border-box;
        "
        class="Rectangle 17"
      ></div
      ><p
        style="
          width: 278px;
          height: 122px;
          display: flex;
          position: absolute;
          left: 34px;
          top: 227px;
          justify-content: center;
          text-align: center;
          margin: 0;
          box-sizing: border-box;
          font-size: 20px;
          font-family: SF UI Text;
          font-weight: 400;
          color: white;
          letter-spacing: 0;
          text-overflow: ellipsis;
          overflow: hidden;
        "
        >I will take a bath soon, please wait</p
      ><p
        style="
          width: 278px;
          height: 59px;
          display: flex;
          position: absolute;
          left: 34px;
          top: 170px;
          justify-content: center;
          text-align: center;
          margin: 0;
          box-sizing: border-box;
          font-size: 20px;
          font-family: SF UI Text;
          font-weight: 700;
          color: white;
          letter-spacing: 0;
          text-overflow: ellipsis;
          overflow: hidden;
        "
        >Taking a Bath</p
      ><p
        style="
          width: 176px;
          height: 45px;
          display: flex;
          position: absolute;
          left: 85px;
          top: 347px;
          justify-content: center;
          text-align: center;
          margin: 0;
          box-sizing: border-box;
          font-size: 20px;
          font-family: SF UI Text;
          font-weight: 700;
          color: white;
          letter-spacing: 0;
          text-overflow: ellipsis;
          overflow: hidden;
        "
        >22 - 12 - 2022</p
      ><p
        style="
          display: flex;
          position: absolute;
          left: 78px;
          top: 146px;
          justify-content: center;
          text-align: center;
          margin: 0;
          box-sizing: border-box;
        "
        ><span
          style="
            font-size: 20px;
            font-family: SF UI Text;
            font-weight: 400;
            color: white;
            letter-spacing: 0;
          "
          >Status : </span
        ><span
          style="
            font-size: 20px;
            font-family: SF UI Text;
            font-weight: 400;
            color: #08d404;
            letter-spacing: 0;
          "
          >Completed</span
        ></p
      ></div
    ></div
  ></div
>

{% endblock content %}